dataset:
  spacing: [2.5, 2.5, 2.5] # [x, y, z], mm
  value_range: [-1024, 1500] # [min, max], HU scale
  resolution: [128, 128, 128] # [x, y, z]
  block_size: [48, 48, 48] # [x, y, z]

projector:
  n_porjections: 2

  # system configuration
  DSD: 1500 # distance source detector (mm)
  DSO: 1100  # distance source origin   (mm)

  # detector parameters
  nDetector: [256, 256] # number of pixels (px)
  dDetector: [2.0, 2.0] # size of each pixel (mm)

  # image parameters
  nVoxel: [128, 128, 128] # number of voxels (vx) [x, y, z]
  dVoxel: [2.5, 2.5, 2.5] # size of each voxel (mm)

  # offsets
  offOrigin: [0, 0, 0] # offset of image from origin (mm) [x, y, z]
  offDetector: [0, 0] # offset of detector (only in two direction) (mm) [u, v]

  # Auxiliary
  accuracy: 0.5 # accuracy of FWD proj (vx/sample)

  # Mode
  mode: cone # x-ray source mode parallel/cone
  filter: null

  # Angles
  total_angle: 180 # total angle (degree)
  start_angle: 0   # start angle (degree)
